bloques:
  derecha:
    candidatos:
    - handle: '@PalomaValenciaL'
      id: '149281495'
      nombre: Paloma Valencia
      partido: CD
      rol: Candidata presidencial
    - handle: '@ABDELAESPRIELLA'
      id: '1657059045956517897'
      nombre: Abelardo De La Espriella
      partido: MSN
      rol: Candidato presidencial
    cuentas_asociadas:
    - handle: '@JDOviedoAr'
      id: '219434063'
      rol: Candidato vicepresidencia Paloma Valencia
    - handle: '@CeDemocratico'
      id: '1115440213'
      rol: Partido Centro Democratico
    - handle: '@AlvaroUribeVel'
      id: '61097151'
      rol: Expresidente
  izquierda:
    candidatos:
    - handle: '@IvanCepedaCast'
      id: '98781946'
      nombre: Ivan Cepeda
      partido: PH
      rol: Candidato presidencial
    cuentas_asociadas:
    - handle: '@petrogustavo'
      id: '49849732'
      rol: Presidente
    - handle: '@PizarroMariaJo'
      id: '1362851972'
      rol: Lider de izquierda
    - handle: '@GustavoBolivar'
      id: '50981729'
      rol: Lider de izquierda
    - handle: '@PactoHistorico'
      id: '998190549353017345'
      rol: Partido politico izquierda
otros_candidatos:
- nombre: Sergio Fajardo
  partido: D&C
- nombre: Juan Manuel Galan
  partido: NL
- nombre: German Vargas Lleras
  partido: CR
